valor1=int(input('Digite um valor: '))
print(valor1 * 1)
print(valor1 * 2)
print(valor1 * 3)
print(valor1 * 4)
print(valor1 * 5)
print(valor1 * 6)
print(valor1 * 7)
print(valor1 * 8)
print(valor1 * 9)
print(valor1 * 10)
